version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    container_name: springbootcourse
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springbootcourse
      MYSQL_USER: andre
      MYSQL_PASSWORD: welcome
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"






