spring:
  datasource:
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springbootcourse?useTimezone=true&serverTimezone=UTC
    username: andre
    password: welcome
#TODO: Remove password from yaml file.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false